spring:
  application:
    name: coupon
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/soma
    username: root
    password:
  sql:
    init:
      mode: always
